### ISSUE TITLE
LessIOSecurityManager is depending on Log4J

### ISSUE THREAD

**Issue by gehel** [wealthfront/kawala#9]
I just started using LessIOSecurityManager for [jmxtrans](https://github.com/jmxtrans/jmxtrans). The concept seems promising and I hope to improve our unit tests (our unit tests really need some love). Only issue is the dependency on log4j, which generate a log of crap in the build logs as it conflicts with our use of slf4j / logback.

I'm tempted to copy the code of LessIOSecurityManager directly in our project, but that seems like an ugly solution. Or for the project and reduce it to a minimal subset of features / dependencies, but that does not seem much better.

Is there any chance that you would extract a minimal artifact that could be more easily reused in other projects?

**Comment by sfritz** [comment]
You can redirect the log4j output to slf4j/logback by replacing the log4j jar with log4j-over-slf4j, as described on this page: http://www.slf4j.org/legacy.html

**Comment by gehel** [comment]
You're right, I forgot about that. Still, do you think there is any chance to get a version of kawala-testing with a more minimal view in term of packaging and dependencies? I would still be interested...

**Comment by sfritz** [comment]
I agree that Commons Logging and a direct dependency on Log4J isn't the optimal choice for a library these days, but it's fairly common in projects that have been around for a while, and we use it heavily internally. TBH it's unlikely to change in the near future.

This problem comes up so often that SLF4J made it a priority to provide a painless workaround that has almost no performance impact.

**Comment by gehel** [comment]
Not many chance of a standalone version of LesIOSecurityManager in the near future, good workarounds existing, as the OP, I'll close this for the moment...
